version: "3"

tasks:
  default:
    cmds:
      - task: generate
  generate:
    aliases:
      - proto
    desc: "Generate code from proto files"
    cmds:
      - protoc -I ./proto \
        --go_out ./proto --go_opt paths=source_relative \
        --go-grpc_out ./proto --go-grpc_opt paths=source_relative \
        --grpc-gateway_out ./proto --grpc-gateway_opt paths=source_relative \
        ./proto/test-task.proto
